language: node_js

node_js:
  - "4"
  - "5"
  - "6"

branches:
  only:
    - master
    - /^greenkeeper-.*$/

script:
  - npm run lint
  - npm run typecheck
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
